### ISSUE TITLE
Evitar mixed content

### ISSUE THREAD

**Issue by dacmail** [politicalwatch/tipi-backend#7]
@pr3ssh para evitar el mixed content creo que sería mejor enviar cualquier URL que vaya a ser linkada sin el protocolo, por ejemplo en https://api.dev.parlamento2030.es/deputies/:

`image:` "http://www.congreso.es/wc/htdocs/web/img/diputados/151_14.jpg", `

debería ser:

`image: "//www.congreso.es/wc/htdocs/web/img/diputados/151_14.jpg",`

**Comment by pr3ssh** [comment]
@dacmail Eso se suele meter en el backend o debería éste mostrar el recurso con el protocolo?

**Comment by dacmail** [comment]
@pr3ssh no entiendo tu pregunta, pero me estoy dando cuenta que congreso.es no tiene SSL XDDDD así que no va a haber forma de evitar el mixed content. :(

**Comment by pr3ssh** [comment]
O_o
